name: Export KiCad Outputs

on:
  push:

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install KiCad 9
        run: |
          sudo add-apt-repository --yes ppa:kicad/kicad-dev-nightly
          sudo apt update
          sudo apt install -y kicad-nightly

      - name: Check KiCad
        run: kicad-cli version

      - name: Show files
        run: find .

      - name: Create output directory
        run: mkdir output

      - name: Export schematic PDF
        run: |
          kicad-cli sch export pdf \
            hardware/auto_test/auto_test.kicad_sch \
            --output output/schematic.pdf

      - name: Export PCB PDF
        run: |
          kicad-cli pcb export pdf \
            hardware/auto_test/auto_test.kicad_pcb \
            --output output/pcb.pdf

      - name: Upload outputs
        uses: actions/upload-artifact@v4
        with:
          name: kicad-output
          path: output/